### ISSUE TITLE
Planificación de servidor de base de datos

### ISSUE THREAD

**Issue by miguelp123** [ISWPOLI/CASABASE#43]
Como:Director de carrera de ingeniería de sistemas .
Quiero: Que se realice una adecuada planificación de creación de un servidor de base de datos
De forma que: Se pueda implementar un servidor de calidad para el proyecto. 

**Tareas**

- [x] #17 Definir las políticas
- [x] #18 definición de responsabilidades
- [x] #19 Definición de copias de seguridad
- [x] #20 Cronograma del servidor de base de datos.

**Comment by miguelp123** [comment]
Esta Características se cierra por el cumplimiento de todas las tareas
